services:
  # FastAPI Application Service
  inference-api:
    build: .
    platform: linux/amd64
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    volumes:
      - .:/app
    command: uv run fastapi dev src/main.py --host 0.0.0.0 --port 8000
